/**
 * Lowercase country/territory phrases → ISO 3166-1 alpha-2 ids from `world-ios.svg` paths.
 * Regenerate when the SVG changes: `node scripts/generate-world-country-map.mjs`
 */

export const COUNTRY_TO_ISO: Record<string, string> = {
  uk: "GB",
  car: "CF",
  drc: "CD",
  usa: "US",
  chad: "TD",
  cuba: "CU",
  dprk: "KP",
  fiji: "FJ",
  iran: "IR",
  iraq: "IQ",
  laos: "LA",
  mali: "ML",
  oman: "OM",
  peru: "PE",
  togo: "TG",
  aruba: "AW",
  benin: "BJ",
  burma: "MM",
  chile: "CL",
  china: "CN",
  congo: "CG",
  egypt: "EG",
  gabon: "GA",
  ghana: "GH",
  haiti: "HT",
  india: "IN",
  italy: "IT",
  japan: "JP",
  kenya: "KE",
  korea: "KR",
  libya: "LY",
  malta: "MT",
  nauru: "NR",
  nepal: "NP",
  niger: "NE",
  qatar: "QA",
  spain: "ES",
  sudan: "SD",
  syria: "SY",
  tonga: "TO",
  wales: "GB",
  yemen: "YE",
  angola: "AO",
  belize: "BZ",
  bhutan: "BT",
  bosnia: "BA",
  brazil: "BR",
  brunei: "BN",
  canada: "CA",
  curaco: "CW",
  cyprus: "CY",
  france: "FR",
  gambia: "GM",
  greece: "GR",
  guinea: "GN",
  guyana: "GY",
  israel: "IL",
  jordan: "JO",
  kuwait: "KW",
  latvia: "LV",
  malawi: "MW",
  mexico: "MX",
  norway: "NO",
  panama: "PA",
  poland: "PL",
  russia: "RU",
  rwanda: "RW",
  serbia: "RS",
  sweden: "SE",
  taiwan: "TW",
  turkey: "TR",
  uganda: "UG",
  zambia: "ZM",
  albania: "AL",
  algeria: "DZ",
  america: "US",
  andorra: "AD",
  armenia: "AM",
  austria: "AT",
  bahamas: "BS",
  belarus: "BY",
  belgium: "BE",
  bermuda: "BM",
  bolivia: "BO",
  britain: "GB",
  burundi: "BI",
  comoros: "KM",
  croatia: "HR",
  curacao: "CW",
  "curaçao": "CW",
  czechia: "CZ",
  denmark: "DK",
  ecuador: "EC",
  england: "GB",
  eritrea: "ER",
  estonia: "EE",
  finland: "FI",
  georgia: "GE",
  germany: "DE",
  grenada: "GD",
  hungary: "HU",
  iceland: "IS",
  ireland: "IE",
  jamaica: "JM",
  "lao pdr": "LA",
  lebanon: "LB",
  lesotho: "LS",
  liberia: "LR",
  mayotte: "YT",
  moldova: "MD",
  morocco: "MA",
  myanmar: "MM",
  namibia: "NA",
  nigeria: "NG",
  reunion: "RE",
  "réunion": "RE",
  romania: "RO",
  senegal: "SN",
  somalia: "SO",
  tunisia: "TN",
  ukraine: "UA",
  uruguay: "UY",
  vanuatu: "VU",
  vietnam: "VN",
  anguilla: "AI",
  barbados: "BB",
  botswana: "BW",
  bulgaria: "BG",
  cambodia: "KH",
  cameroon: "CM",
  colombia: "CO",
  djibouti: "DJ",
  dominica: "DM",
  "dr congo": "CD",
  eswatini: "SZ",
  ethiopia: "ET",
  honduras: "HN",
  malaysia: "MY",
  maldives: "MV",
  mongolia: "MN",
  pakistan: "PK",
  paraguay: "PY",
  pitcairn: "PN",
  portugal: "PT",
  "s. sudan": "SS",
  scotland: "GB",
  slovakia: "SK",
  slovenia: "SI",
  suriname: "SR",
  tanzania: "TZ",
  thailand: "TH",
  "viet nam": "VN",
  zimbabwe: "ZW",
  argentina: "AR",
  australia: "AU",
  "cayman is": "KY",
  "czech rep": "CZ",
  "faeroe is": "FO",
  falklands: "FK",
  greenland: "GL",
  guatemala: "GT",
  "hong kong": "HK",
  indonesia: "ID",
  lithuania: "LT",
  macedonia: "MK",
  mauritius: "MU",
  nicaragua: "NI",
  palestine: "PS",
  singapore: "SG",
  "sri lanka": "LK",
  swaziland: "SZ",
  venezuela: "VE",
  "w. sahara": "EH",
  azerbaijan: "AZ",
  bangladesh: "BD",
  "cabo verde": "CV",
  "cape verde": "CV",
  "costa rica": "CR",
  "east timor": "TL",
  "eq. guinea": "GQ",
  guadeloupe: "GP",
  kazakhstan: "KZ",
  kyrgyzstan: "KG",
  luxembourg: "LU",
  madagascar: "MG",
  martinique: "MQ",
  mauritania: "MR",
  montenegro: "ME",
  montserrat: "MS",
  mozambique: "MZ",
  seychelles: "SC",
  "solomon is": "SB",
  "st vincent": "VC",
  tajikistan: "TJ",
  uzbekistan: "UZ",
  afghanistan: "AF",
  "el salvador": "SV",
  "falkland is": "FK",
  "ivory coast": "CI",
  netherlands: "NL",
  "new zealand": "NZ",
  "north korea": "KP",
  philippines: "PH",
  "pitcairn is": "PN",
  "puerto rico": "PR",
  "saint lucia": "LC",
  "south korea": "KR",
  "south sudan": "SS",
  switzerland: "CH",
  "timor leste": "TL",
  "timor-leste": "TL",
  "burkina faso": "BF",
  "saint martin": "SX",
  "saudi arabia": "SA",
  "sierra leone": "SL",
  "sint maarten": "SX",
  "south africa": "ZA",
  turkmenistan: "TM",
  "cote d ivoire": "CI",
  "côte d'ivoire": "CI",
  "dem rep congo": "CD",
  "dominican rep": "DO",
  "faroe islands": "FO",
  "fr. polynesia": "PF",
  "french guiana": "GF",
  "great britain": "GB",
  "guinea-bissau": "GW",
  liechtenstein: "LI",
  "new caledonia": "NC",
  "united states": "US",
  "canary islands": "IC",
  "cayman islands": "KY",
  "czech republic": "CZ",
  "faeroe islands": "FO",
  "korea republic": "KR",
  "u.s. virgin is": "VI",
  "united kingdom": "GB",
  "western sahara": "EH",
  "bosnia and herz": "BA",
  "dem. rep. congo": "CD",
  "dem. rep. korea": "KP",
  "solomon islands": "SB",
  "antigua and barb": "AG",
  "falkland islands": "FK",
  "french polynesia": "PF",
  "northern ireland": "GB",
  "papua new guinea": "PG",
  "pitcairn islands": "PN",
  "turks and caicos": "TC",
  "british virgin is": "VG",
  "equatorial guinea": "GQ",
  "republic of korea": "KR",
  "st. vin. and gren": "VC",
  "us virgin islands": "VI",
  "dominican republic": "DO",
  "st kitts and nevis": "KN",
  "antigua and barbuda": "AG",
  "central african rep": "CF",
  "st. kitts and nevis": "KN",
  "trinidad and tobago": "TT",
  "turks and caicos is": "TC",
  "united arab emirates": "AE",
  "saint kitts and nevis": "KN",
  "são tomé and principe": "ST",
  "bosnia and herzegovina": "BA",
  "british virgin islands": "VG",
  "central african republic": "CF",
  "turks and caicos islands": "TC",
  "united states of america": "US",
  "united states virgin islands": "VI",
  "st vincent and the grenadines": "VC",
  "democratic republic of the congo": "CD",
  "saint vincent and the grenadines": "VC",
  "democratic people's republic of korea": "KP",
};

export const WORLD_MAP_COUNTRY_COUNT = 211;
