/**
 * Data for /s/ primitive demos (semantic colors, spacing scale, typography samples).
 * Semantic tokens mirror design-tokens output in generated/tokens.css :root.
 */

export type SemanticColorCategory = { title: string; description?: string; tokens: string[] };

/** Broad groupings for the Colors primitive page — use only semantic tokens in UI. */
export const semanticColorCategories: SemanticColorCategory[] = [
  {
    title: 'Foreground',
    description: 'Text and icon colors on surfaces.',
    tokens: [
      'foreground-primary',
      'foreground-secondary',
      'foreground-inverse',
      'foreground-intent-positive',
      'foreground-intent-caution',
      'foreground-intent-negative',
      'foreground-intent-info',
    ],
  },
  {
    title: 'Surface',
    description: 'Layers, fills, scrims, and intent-tinted surfaces.',
    tokens: [
      'surface-1',
      'surface-2',
      'surface-3',
      'surface-4',
      'surface-5',
      'surface-6',
      'surface-brand',
      'surface-inverse',
      'surface-backdrop',
      'surface-border-5',
      'surface-shadow-4-color',
      'surface-shadow-5-color',
      'surface-intent-positive-default',
      'surface-intent-positive-subtle',
      'surface-intent-caution-default',
      'surface-intent-caution-subtle',
      'surface-intent-negative-default',
      'surface-intent-negative-subtle',
      'surface-intent-info-default',
      'surface-intent-info-subtle',
    ],
  },
  {
    title: 'Border',
    description: 'Strokes and separators.',
    tokens: [
      'border-strong',
      'border-subtle',
      'border-muted',
      'border-intent-positive',
      'border-intent-caution',
      'border-intent-negative',
      'border-intent-info',
    ],
  },
  {
    title: 'Focus & links',
    tokens: ['focus-ring', 'misc-link'],
  },
  {
    title: 'Interactive — solid, outline, subtle',
    description: 'Default control states (neutral).',
    tokens: [
      'interactive-solid-default',
      'interactive-solid-hover',
      'interactive-solid-press',
      'interactive-solid-select',
      'interactive-outline-default',
      'interactive-outline-hover',
      'interactive-outline-press',
      'interactive-outline-focus',
      'interactive-outline-select',
      'interactive-subtle-default',
      'interactive-subtle-hover',
      'interactive-subtle-press',
      'interactive-subtle-focus',
      'interactive-subtle-select',
    ],
  },
  {
    title: 'Interactive — ghost',
    description: 'Transparent fills; subtle on hover.',
    tokens: [
      'interactive-ghost-default',
      'interactive-ghost-hover',
      'interactive-ghost-press',
      'interactive-ghost-focus',
      'interactive-ghost-select',
      'interactive-ghost-inverse-default',
      'interactive-ghost-inverse-hover',
      'interactive-ghost-inverse-press',
      'interactive-ghost-inverse-focus',
      'interactive-ghost-inverse-select',
    ],
  },
  {
    title: 'Interactive — intent (positive)',
    tokens: [
      'interactive-intent-positive-solid-default',
      'interactive-intent-positive-solid-hover',
      'interactive-intent-positive-solid-press',
      'interactive-intent-positive-outline-default',
      'interactive-intent-positive-outline-hover',
      'interactive-intent-positive-outline-press',
      'interactive-intent-positive-outline-focus',
      'interactive-intent-positive-outline-select',
      'interactive-intent-positive-subtle-default',
      'interactive-intent-positive-subtle-hover',
      'interactive-intent-positive-subtle-press',
      'interactive-intent-positive-subtle-focus',
      'interactive-intent-positive-subtle-select',
    ],
  },
  {
    title: 'Interactive — intent (caution)',
    tokens: [
      'interactive-intent-caution-solid-default',
      'interactive-intent-caution-solid-hover',
      'interactive-intent-caution-solid-press',
      'interactive-intent-caution-outline-default',
      'interactive-intent-caution-outline-hover',
      'interactive-intent-caution-outline-press',
      'interactive-intent-caution-outline-focus',
      'interactive-intent-caution-outline-select',
      'interactive-intent-caution-subtle-default',
      'interactive-intent-caution-subtle-hover',
      'interactive-intent-caution-subtle-press',
      'interactive-intent-caution-subtle-focus',
      'interactive-intent-caution-subtle-select',
    ],
  },
  {
    title: 'Interactive — intent (error)',
    tokens: [
      'interactive-intent-error-solid-default',
      'interactive-intent-error-solid-hover',
      'interactive-intent-error-solid-press',
      'interactive-intent-error-outline-default',
      'interactive-intent-error-outline-hover',
      'interactive-intent-error-outline-press',
      'interactive-intent-error-outline-focus',
      'interactive-intent-error-outline-select',
      'interactive-intent-error-subtle-default',
      'interactive-intent-error-subtle-hover',
      'interactive-intent-error-subtle-press',
      'interactive-intent-error-subtle-focus',
      'interactive-intent-error-subtle-select',
    ],
  },
  {
    title: 'Interactive — intent (info)',
    tokens: [
      'interactive-intent-info-solid-default',
      'interactive-intent-info-solid-hover',
      'interactive-intent-info-solid-press',
      'interactive-intent-info-outline-default',
      'interactive-intent-info-outline-hover',
      'interactive-intent-info-outline-press',
      'interactive-intent-info-outline-focus',
      'interactive-intent-info-outline-select',
      'interactive-intent-info-subtle-default',
      'interactive-intent-info-subtle-hover',
      'interactive-intent-info-subtle-press',
      'interactive-intent-info-subtle-focus',
      'interactive-intent-info-subtle-select',
    ],
  },
];

/** Spacing scale keys matching --spacing-* in tokens.css */
export const spacingScaleKeys = [
  '0', '2', '4', '6', '8', '10', '12', '14', '16', '18', '20', '22', '24', '26', '28', '30', '32',
  '34', '36', '38', '40', '42', '44', '46', '48', '50', '52', '54', '56', '58', '60', '64', '68',
  '72', '80', '88', '96', '102', '110', '126', '142', '158',
] as const;

export type TypographySample = { className: string; sample: string; tokenHint: string };
export type TypographySection = { title: string; subtitle?: string; items: TypographySample[] };

export const typographySections: TypographySection[] = [
  {
    title: 'Display',
    subtitle: 'Saans — marketing / hero',
    items: [
      { className: 'ds-type-display-l', sample: 'Display L', tokenHint: '--type-display-l-*' },
      { className: 'ds-type-display-s', sample: 'Display S', tokenHint: '--type-display-s-*' },
    ],
  },
  {
    title: 'Headline',
    subtitle: 'Saans — section titles',
    items: [
      { className: 'ds-type-headline-xl', sample: 'Headline XL', tokenHint: '--type-headline-xl-*' },
      { className: 'ds-type-headline-l', sample: 'Headline L', tokenHint: '--type-headline-l-*' },
      { className: 'ds-type-headline-m', sample: 'Headline M', tokenHint: '--type-headline-m-*' },
      { className: 'ds-type-headline-s', sample: 'Headline S', tokenHint: '--type-headline-s-*' },
      { className: 'ds-type-headline-xs', sample: 'Headline XS', tokenHint: '--type-headline-xs-*' },
    ],
  },
  {
    title: 'Label',
    subtitle: 'Google Sans Flex — UI labels',
    items: [
      { className: 'ds-type-label-xl-short', sample: 'Label XL short', tokenHint: '--type-label-xl-*' },
      { className: 'ds-type-label-xl-tall', sample: 'Label XL tall', tokenHint: '--type-label-xl-*' },
      { className: 'ds-type-label-l-short', sample: 'Label L short', tokenHint: '--type-label-l-*' },
      { className: 'ds-type-label-l-tall', sample: 'Label L tall', tokenHint: '--type-label-l-*' },
      { className: 'ds-type-label-m-short', sample: 'Label M short', tokenHint: '--type-label-m-*' },
      { className: 'ds-type-label-m-tall', sample: 'Label M tall', tokenHint: '--type-label-m-*' },
      { className: 'ds-type-label-s-short', sample: 'Label S short', tokenHint: '--type-label-s-*' },
      { className: 'ds-type-label-s-tall', sample: 'Label S tall', tokenHint: '--type-label-s-*' },
      { className: 'ds-type-label-xs-short', sample: 'Label XS short', tokenHint: '--type-label-xs-*' },
      { className: 'ds-type-label-xs-tall', sample: 'Label XS tall', tokenHint: '--type-label-xs-*' },
    ],
  },
  {
    title: 'Body',
    subtitle: 'Google Sans Flex — paragraphs and UI copy',
    items: [
      { className: 'ds-type-body-xl-short', sample: 'Body XL short', tokenHint: '--type-body-xl-*' },
      { className: 'ds-type-body-xl-tall', sample: 'Body XL tall', tokenHint: '--type-body-xl-*' },
      { className: 'ds-type-body-l-short', sample: 'Body L short', tokenHint: '--type-body-l-*' },
      { className: 'ds-type-body-l-tall', sample: 'Body L tall', tokenHint: '--type-body-l-*' },
      { className: 'ds-type-body-m-short', sample: 'Body M short', tokenHint: '--type-body-m-*' },
      { className: 'ds-type-body-m-tall', sample: 'Body M tall', tokenHint: '--type-body-m-*' },
      { className: 'ds-type-body-s-short', sample: 'Body S short', tokenHint: '--type-body-s-*' },
      { className: 'ds-type-body-s-tall', sample: 'Body S tall', tokenHint: '--type-body-s-*' },
      { className: 'ds-type-body-xs-short', sample: 'Body XS short', tokenHint: '--type-body-xs-*' },
      { className: 'ds-type-body-xs-tall', sample: 'Body XS tall', tokenHint: '--type-body-xs-*' },
    ],
  },
  {
    title: 'Code',
    subtitle: 'Google Sans Code — monospace',
    items: [
      { className: 'ds-type-code-xl-short', sample: 'code-xl-short', tokenHint: '--type-code-xl-*' },
      { className: 'ds-type-code-xl-tall', sample: 'code-xl-tall', tokenHint: '--type-code-xl-*' },
      { className: 'ds-type-code-l-short', sample: 'code-l-short', tokenHint: '--type-code-l-*' },
      { className: 'ds-type-code-l-tall', sample: 'code-l-tall', tokenHint: '--type-code-l-*' },
      { className: 'ds-type-code-m-short', sample: 'code-m-short', tokenHint: '--type-code-m-*' },
      { className: 'ds-type-code-m-tall', sample: 'code-m-tall', tokenHint: '--type-code-m-*' },
      { className: 'ds-type-code-s-short', sample: 'code-s-short', tokenHint: '--type-code-s-*' },
      { className: 'ds-type-code-s-tall', sample: 'code-s-tall', tokenHint: '--type-code-s-*' },
      { className: 'ds-type-code-xs-short', sample: 'code-xs-short', tokenHint: '--type-code-xs-*' },
      { className: 'ds-type-code-xs-tall', sample: 'code-xs-tall', tokenHint: '--type-code-xs-*' },
    ],
  },
];
